export const ACCESS_TOKEN_EXPIRES_IN = "15m";

export const REFRESH_TOKEN_EXPIRES_IN = "30d";

export const EMAIL_VERIFICATION_EXPIRES_IN_MINUTES = 15;

export const PASSWORD_RESET_EXPIRES_IN_MINUTES = 15;
